name: Test Contract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y npm
        sudo npm install -g ganache-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with brownie
      run: |
        brownie test --coverage
    - name: Setup deploy_account
      run: |
        echo $DEPLOY_ACCOUNT > ./account.json
        brownie accounts import "deploy_account" ./account.json
        rm ./account.json
    - name: Run Deploy
      run: |
        brownie scripts/deploy_token.py --network ropsten
